baseurl = "https://example.com"
title = "gohugo.io"
author = "Kosmos"
copyright = "Copyright © Nikodem Glembin, wheu and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Steve Francia"
introDescription = "Cześć, tutaj Nikodem a to projekt na informatyke"
contentSharing = "Kosmos."

[social]
instagram = "realmattbutton"
linkedin = "matt-button-2225537"
twitter = "realmattbutton"

